INSERT INTO currency (name, code, symbol) VALUES ('Leke', 'ALL', 'Lek');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'USD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Afghanis', 'AFN', '؋');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'ARS', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Guilders', 'AWG', 'ƒ');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'AUD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('New Manats', 'AZN', 'ман');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'BSD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'BBD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Rubles', 'BYR', 'p.');
INSERT INTO currency (name, code, symbol) VALUES ('Euro', 'EUR', '€');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'BZD', 'BZ$');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'BMD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Bolivianos', 'BOB', '$b');
INSERT INTO currency (name, code, symbol) VALUES ('Convertible Marka', 'BAM', 'KM');
INSERT INTO currency (name, code, symbol) VALUES ('Pula', 'BWP', 'P');
INSERT INTO currency (name, code, symbol) VALUES ('Leva', 'BGN', 'лв');
INSERT INTO currency (name, code, symbol) VALUES ('Reais', 'BRL', 'R$');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'GBP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'BND', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Riels', 'KHR', '៛');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'CAD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'KYD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'CLP', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Yuan Renminbi', 'CNY', '¥');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'COP', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Colón', 'CRC', '₡');
INSERT INTO currency (name, code, symbol) VALUES ('Kuna', 'HRK', 'kn');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'CUP', '₱');
INSERT INTO currency (name, code, symbol) VALUES ('Koruny', 'CZK', 'Kč');
INSERT INTO currency (name, code, symbol) VALUES ('Kroner', 'DKK', 'kr');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'DOP ', 'RD$');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'XCD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'EGP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Colones', 'SVC', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'FKP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'FJD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Cedis', 'GHC', '¢');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'GIP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Quetzales', 'GTQ', 'Q');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'GGP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'GYD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Lempiras', 'HNL', 'L');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'HKD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Forint', 'HUF', 'Ft');
INSERT INTO currency (name, code, symbol) VALUES ('Kronur', 'ISK', 'kr');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'INR', 'Rp');
INSERT INTO currency (name, code, symbol) VALUES ('Rupiahs', 'IDR', 'Rp');
INSERT INTO currency (name, code, symbol) VALUES ('Rials', 'IRR', '﷼');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'IMP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('New Shekels', 'ILS', '₪');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'JMD', 'J$');
INSERT INTO currency (name, code, symbol) VALUES ('Yen', 'JPY', '¥');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'JEP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Tenge', 'KZT', 'лв');
INSERT INTO currency (name, code, symbol) VALUES ('Won', 'KPW', '₩');
INSERT INTO currency (name, code, symbol) VALUES ('Won', 'KRW', '₩');
INSERT INTO currency (name, code, symbol) VALUES ('Soms', 'KGS', 'лв');
INSERT INTO currency (name, code, symbol) VALUES ('Kips', 'LAK', '₭');
INSERT INTO currency (name, code, symbol) VALUES ('Lati', 'LVL', 'Ls');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'LBP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'LRD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Switzerland Francs', 'CHF', 'CHF');
INSERT INTO currency (name, code, symbol) VALUES ('Litai', 'LTL', 'Lt');
INSERT INTO currency (name, code, symbol) VALUES ('Denars', 'MKD', 'ден');
INSERT INTO currency (name, code, symbol) VALUES ('Ringgits', 'MYR', 'RM');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'MUR', '₨');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'MXN', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Tugriks', 'MNT', '₮');
INSERT INTO currency (name, code, symbol) VALUES ('Meticais', 'MZN', 'MT');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'NAD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'NPR', '₨');
INSERT INTO currency (name, code, symbol) VALUES ('Guilders', 'ANG', 'ƒ');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'NZD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Cordobas', 'NIO', 'C$');
INSERT INTO currency (name, code, symbol) VALUES ('Nairas', 'NGN', '₦');
INSERT INTO currency (name, code, symbol) VALUES ('Krone', 'NOK', 'kr');
INSERT INTO currency (name, code, symbol) VALUES ('Rials', 'OMR', '﷼');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'PKR', '₨');
INSERT INTO currency (name, code, symbol) VALUES ('Balboa', 'PAB', 'B/.');
INSERT INTO currency (name, code, symbol) VALUES ('Guarani', 'PYG', 'Gs');
INSERT INTO currency (name, code, symbol) VALUES ('Nuevos Soles', 'PEN', 'S/.');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'PHP', 'Php');
INSERT INTO currency (name, code, symbol) VALUES ('Zlotych', 'PLN', 'zł');
INSERT INTO currency (name, code, symbol) VALUES ('Rials', 'QAR', '﷼');
INSERT INTO currency (name, code, symbol) VALUES ('New Lei', 'RON', 'lei');
INSERT INTO currency (name, code, symbol) VALUES ('Rubles', 'RUB', 'руб');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'SHP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Riyals', 'SAR', '﷼');
INSERT INTO currency (name, code, symbol) VALUES ('Dinars', 'RSD', 'Дин.');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'SCR', '₨');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'SGD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'SBD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Shillings', 'SOS', 'S');
INSERT INTO currency (name, code, symbol) VALUES ('Rand', 'ZAR', 'R');
INSERT INTO currency (name, code, symbol) VALUES ('Rupees', 'LKR', '₨');
INSERT INTO currency (name, code, symbol) VALUES ('Kronor', 'SEK', 'kr');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'SRD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Pounds', 'SYP', '£');
INSERT INTO currency (name, code, symbol) VALUES ('New Dollars', 'TWD', 'NT$');
INSERT INTO currency (name, code, symbol) VALUES ('Baht', 'THB', '฿');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'TTD', 'TT$');
INSERT INTO currency (name, code, symbol) VALUES ('Lira', 'TRY', 'TL');
INSERT INTO currency (name, code, symbol) VALUES ('Liras', 'TRL', '£');
INSERT INTO currency (name, code, symbol) VALUES ('Dollars', 'TVD', '$');
INSERT INTO currency (name, code, symbol) VALUES ('Hryvnia', 'UAH', '₴');
INSERT INTO currency (name, code, symbol) VALUES ('Pesos', 'UYU', '$U');
INSERT INTO currency (name, code, symbol) VALUES ('Sums', 'UZS', 'лв');
INSERT INTO currency (name, code, symbol) VALUES ('Bolivares Fuertes', 'VEF', 'Bs');
INSERT INTO currency (name, code, symbol) VALUES ('Dong', 'VND', '₫');
INSERT INTO currency (name, code, symbol) VALUES ('Rials', 'YER', '﷼');
INSERT INTO currency (name, code, symbol) VALUES ('Zimbabwe Dollars', 'ZWD', 'Z$');

------------------------------------------------------------------------------

INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AF','Afghanistan','AFG',93);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AL','Albania','ALB',355);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DZ','Algeria','DZA',213);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AS','American Samoa','ASM',1684);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AD','Andorra','AND',376);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AO','Angola','AGO',244);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AI','Anguilla','AIA',1264);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AQ','Antarctica',NULL,0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AG','Antigua and Barbuda','ATG',1268);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AR','Argentina','ARG',54);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AM','Armenia','ARM',374);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AW','Aruba','ABW',297);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AU','Australia','AUS',61);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AT','Austria','AUT',43);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AZ','Azerbaijan','AZE',994);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BS','Bahamas','BHS',1242);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BH','Bahrain','BHR',973);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BD','Bangladesh','BGD',880);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BB','Barbados','BRB',1246);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BY','Belarus','BLR',375);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BE','Belgium','BEL',32);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BZ','Belize','BLZ',501);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BJ','Benin','BEN',229);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BM','Bermuda','BMU',1441);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BT','Bhutan','BTN',975);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BO','Bolivia','BOL',591);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BA','Bosnia and Herzegovina','BIH',387);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BW','Botswana','BWA',267);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BV','Bouvet Island',NULL,0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BR','Brazil','BRA',55);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IO','British Indian Ocean Territory',NULL,246);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BN','Brunei Darussalam','BRN',673);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BG','Bulgaria','BGR',359);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BF','Burkina Faso','BFA',226);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BI','Burundi','BDI',257);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KH','Cambodia','KHM',855);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CM','Cameroon','CMR',237);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CA','Canada','CAN',1);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CV','Cape Verde','CPV',238);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KY','Cayman Islands','CYM',1345);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CF','Central African Republic','CAF',236);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TD','Chad','TCD',235);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CL','Chile','CHL',56);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CN','China','CHN',86);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CX','Christmas Island',NULL,61);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CC','Cocos (Keeling) Islands',NULL,672);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CO','Colombia','COL',57);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KM','Comoros','COM',269);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CG','Congo','COG',242);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CD','Congo, the Democratic Republic of the','COD',242);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CK','Cook Islands','COK',682);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CR','Costa Rica','CRI',506);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CI','Cote D''Ivoire','CIV',225);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HR','Croatia','HRV',385);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CU','Cuba','CUB',53);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CY','Cyprus','CYP',357);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CZ','Czech Republic','CZE',420);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DK','Denmark','DNK',45);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DJ','Djibouti','DJI',253);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DM','Dominica','DMA',1767);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DO','Dominican Republic','DOM',1809);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('EC','Ecuador','ECU',593);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('EG','Egypt','EGY',20);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SV','El Salvador','SLV',503);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GQ','Equatorial Guinea','GNQ',240);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ER','Eritrea','ERI',291);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('EE','Estonia','EST',372);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ET','Ethiopia','ETH',251);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FK','Falkland Islands (Malvinas)','FLK',500);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FO','Faroe Islands','FRO',298);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FJ','Fiji','FJI',679);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FI','Finland','FIN',358);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FR','France','FRA',33);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GF','French Guiana','GUF',594);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PF','French Polynesia','PYF',689);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TF','French Southern Territories',NULL,0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GA','Gabon','GAB',241);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GM','Gambia','GMB',220);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GE','Georgia','GEO',995);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('DE','Germany','DEU',49);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GH','Ghana','GHA',233);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GI','Gibraltar','GIB',350);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GR','Greece','GRC',30);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GL','Greenland','GRL',299);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GD','Grenada','GRD',1473);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GP','Guadeloupe','GLP',590);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GU','Guam','GUM',1671);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GT','Guatemala','GTM',502);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GN','Guinea','GIN',224);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GW','Guinea-Bissau','GNB',245);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GY','Guyana','GUY',592);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HT','Haiti','HTI',509);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HM','Heard Island and Mcdonald Islands',NULL,0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VA','Holy See (Vatican City State)','VAT',39);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HN','Honduras','HND',504);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HK','Hong Kong','HKG',852);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('HU','Hungary','HUN',36);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IS','Iceland','ISL',354);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IN','India','IND',91);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ID','Indonesia','IDN',62);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IR','Iran, Islamic Republic of','IRN',98);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IQ','Iraq','IRQ',964);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IE','Ireland','IRL',353);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IL','Israel','ISR',972);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IT','Italy','ITA',39);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('JM','Jamaica','JAM',1876);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('JP','Japan','JPN',81);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('JO','Jordan','JOR',962);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KZ','Kazakhstan','KAZ',7);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KE','Kenya','KEN',254);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KI','Kiribati','KIR',686);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KP','Korea, Democratic People''s Republic of','PRK',850);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KR','Korea, Republic of','KOR',82);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KW','Kuwait','KWT',965);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KG','Kyrgyzstan','KGZ',996);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LA','Lao People''s Democratic Republic','LAO',856);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LV','Latvia','LVA',371);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LB','Lebanon','LBN',961);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LS','Lesotho','LSO',266);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LR','Liberia','LBR',231);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LY','Libyan Arab Jamahiriya','LBY',218);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LI','Liechtenstein','LIE',423);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LT','Lithuania','LTU',370);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LU','Luxembourg','LUX',352);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MO','Macao','MAC',853);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MK','Macedonia, the Former Yugoslav Republic of','MKD',389);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MG','Madagascar','MDG',261);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MW','Malawi','MWI',265);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MY','Malaysia','MYS',60);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MV','Maldives','MDV',960);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ML','Mali','MLI',223);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MT','Malta','MLT',356);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MH','Marshall Islands','MHL',692);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MQ','Martinique','MTQ',596);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MR','Mauritania','MRT',222);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MU','Mauritius','MUS',230);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('YT','Mayotte',NULL,269);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MX','Mexico','MEX',52);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('FM','Micronesia, Federated States of','FSM',691);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MD','Moldova, Republic of','MDA',373);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MC','Monaco','MCO',377);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MN','Mongolia','MNG',976);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MS','Montserrat','MSR',1664);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MA','Morocco','MAR',212);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MZ','Mozambique','MOZ',258);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MM','Myanmar','MMR',95);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NA','Namibia','NAM',264);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NR','Nauru','NRU',674);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NP','Nepal','NPL',977);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NL','Netherlands','NLD',31);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AN','Netherlands Antilles','ANT',599);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NC','New Caledonia','NCL',687);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NZ','New Zealand','NZL',64);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NI','Nicaragua','NIC',505);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NE','Niger','NER',227);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NG','Nigeria','NGA',234);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NU','Niue','NIU',683);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NF','Norfolk Island','NFK',672);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MP','Northern Mariana Islands','MNP',1670);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('NO','Norway','NOR',47);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('OM','Oman','OMN',968);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PK','Pakistan','PAK',92);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PW','Palau','PLW',680);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PS','Palestinian Territory, Occupied',NULL,970);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PA','Panama','PAN',507);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PG','Papua New Guinea','PNG',675);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PY','Paraguay','PRY',595);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PE','Peru','PER',51);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PH','Philippines','PHL',63);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PN','Pitcairn','PCN',0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PL','Poland','POL',48);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PT','Portugal','PRT',351);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PR','Puerto Rico','PRI',1787);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('QA','Qatar','QAT',974);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('RE','Reunion','REU',262);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('RO','Romania','ROM',40);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('RU','Russian Federation','RUS',70);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('RW','Rwanda','RWA',250);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SH','Saint Helena','SHN',290);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('KN','Saint Kitts and Nevis','KNA',1869);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LC','Saint Lucia','LCA',1758);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('PM','Saint Pierre and Miquelon','SPM',508);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VC','Saint Vincent and the Grenadines','VCT',1784);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('WS','Samoa','WSM',684);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SM','San Marino','SMR',378);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ST','Sao Tome and Principe','STP',239);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SA','Saudi Arabia','SAU',966);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SN','Senegal','SEN',221);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CS','Serbia and Montenegro',NULL,381);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SC','Seychelles','SYC',248);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SL','Sierra Leone','SLE',232);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SG','Singapore','SGP',65);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SK','Slovakia','SVK',421);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SI','Slovenia','SVN',386);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SB','Solomon Islands','SLB',677);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SO','Somalia','SOM',252);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ZA','South Africa','ZAF',27);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GS','South Georgia and the South Sandwich Islands',NULL,0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ES','Spain','ESP',34);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('LK','Sri Lanka','LKA',94);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SD','Sudan','SDN',249);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SR','Suriname','SUR',597);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SJ','Svalbard and Jan Mayen','SJM',47);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SZ','Swaziland','SWZ',268);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SE','Sweden','SWE',46);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CH','Switzerland','CHE',41);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SY','Syrian Arab Republic','SYR',963);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TW','Taiwan, Province of China','TWN',886);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TJ','Tajikistan','TJK',992);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TZ','Tanzania, United Republic of','TZA',255);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TH','Thailand','THA',66);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TL','Timor-Leste',NULL,670);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TG','Togo','TGO',228);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TK','Tokelau','TKL',690);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TO','Tonga','TON',676);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TT','Trinidad and Tobago','TTO',1868);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TN','Tunisia','TUN',216);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TR','Turkey','TUR',90);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TM','Turkmenistan','TKM',7370);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TC','Turks and Caicos Islands','TCA',1649);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('TV','Tuvalu','TUV',688);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('UG','Uganda','UGA',256);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('UA','Ukraine','UKR',380);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AE','United Arab Emirates','ARE',971);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GB','United Kingdom','GBR',44);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('US','United States','USA',1);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('UM','United States Minor Outlying Islands',NULL,1);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('UY','Uruguay','URY',598);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('UZ','Uzbekistan','UZB',998);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VU','Vanuatu','VUT',678);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VE','Venezuela','VEN',58);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VN','Viet Nam','VNM',84);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VG','Virgin Islands, British','VGB',1284);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('VI','Virgin Islands, U.s.','VIR',1340);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('WF','Wallis and Futuna','WLF',681);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('EH','Western Sahara','ESH',212);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('YE','Yemen','YEM',967);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ZM','Zambia','ZMB',260);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ZW','Zimbabwe','ZWE',263);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('RS','Serbia','SRB',381);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AP','Asia / Pacific Region','0  ',0);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('ME','Montenegro','MNE',382);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('AX','Aland Islands','ALA',358);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BQ','Bonaire, Sint Eustatius and Saba','BES',599);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('CW','Curacao','CUW',599);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('GG','Guernsey','GGY',44);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('IM','Isle of Man','IMN',44);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('JE','Jersey','JEY',44);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('XK','Kosovo','---',381);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('BL','Saint Barthelemy','BLM',590);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('MF','Saint Martin','MAF',590);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SX','Sint Maarten','SXM',1);
INSERT INTO public.country (iso,"name",iso3,phone_code) VALUES ('SS','South Sudan','SSD',211);
------------------------------------------------------------------------------

INSERT INTO public.role (role_name, permissions) VALUES ('Administrator', 65535);
INSERT INTO public.role (role_name, permissions) VALUES ('Operator',7);

------------------------------------------------------------------------------

INSERT INTO public.rating_scale (name, value, description) VALUES ('Binary', 2, '{"No:1","Yes:2"}');
INSERT INTO public.rating_scale (name, value, description) VALUES ('Three star', 2, '{"Not my cup of tea:1","OK:2", "Awesome:3"}');
INSERT INTO public.rating_scale (name, value, description) VALUES ('Five star', 2, '{"Not my cup of tea:1", "Expected more:2", "Not Bad:3", "Great:4", "Awesome:5"}');

------------------------------------------------------------------------------

INSERT INTO sysconfig (name, int_value) VALUES('PHOTO_LIMIT_NO', 5);
INSERT INTO sysconfig (name, int_value) VALUES('BOOKING_WAIT_TIME_SECONDS', 900);
INSERT INTO sysconfig (name, int_value) VALUES('BOOKING_DURATION_HOURS', 1);
INSERT INTO sysconfig (name, bool_value) VALUES('CAN_BOOK_ALL_TABLES', TRUE);

------------------------------------------------------------------------------

INSERT INTO public.sysuser (username, passhash, first_name, last_name, surname, address,updated_by) 
VALUES ('smmohan', 'smmohan', 'Murali', 'Mohan', 'Saginala', '501, Brindavan Heights, Joharapuram Road, Kurnool, AP - 518002',1);

------------------------------------------------------------------------------
