package com.omnia.config.model;
// Generated 17 Aug, 2019 12:44:50 AM by Hibernate Tools 5.4.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */

@Entity
@Table(name = "country")
public class Country implements java.io.Serializable {

	@Id
	@Column(name = "iso")
	private String iso;
	
	private String name;
	private String iso3;
	private int phoneCode;

	public Country() {
	}

	public Country(String iso, String name, int phoneCode) {
		this.iso = iso;
		this.name = name;
		this.phoneCode = phoneCode;
	}

	public Country(String iso, String name, String iso3, int phoneCode) {
		this.iso = iso;
		this.name = name;
		this.iso3 = iso3;
		this.phoneCode = phoneCode;
	}

	public String getIso() {
		return this.iso;
	}

	public void setIso(String iso) {
		this.iso = iso;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getIso3() {
		return this.iso3;
	}

	public void setIso3(String iso3) {
		this.iso3 = iso3;
	}

	public int getPhoneCode() {
		return this.phoneCode;
	}

	public void setPhoneCode(int phoneCode) {
		this.phoneCode = phoneCode;
	}

	@Override
	public String toString() {
		return "Country [iso=" + iso + ", name=" + name + ", iso3=" + iso3 + ", phoneCode=" + phoneCode  + "]";
	}
}
